# Generated by Django 6.0.3 on 2026-03-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('emp_type', models.CharField(blank=True, max_length=50)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('address', models.TextField(blank=True)),
                ('education', models.CharField(blank=True, max_length=200)),
                ('skills', models.TextField(blank=True)),
                ('hobbies', models.TextField(blank=True)),
                ('biotag', models.CharField(blank=True, max_length=200)),
                ('ec_name', models.CharField(blank=True, max_length=100)),
                ('ec_relation', models.CharField(blank=True, max_length=50)),
                ('ec_phone', models.CharField(blank=True, max_length=20)),
                ('ec_alt_phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
